package Tampilan;

import Kelas.GameProgress;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Level extends javax.swing.JFrame {
    private final GameProgress progress;

    public Level() {
        this.progress = GameProgress.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu Level - Skor: " + progress.getTotalScore() + 
                " | Nyawa: " + progress.getRemainingLives());        
        setupLevelButtons();   
    }
    
    private void setupLevelButtons() {
        JButton[] levelButtons = {L1Btn, L2Btn, L3Btn, L4Btn, L5Btn};
        
        for (int i = 0; i < levelButtons.length; i++) {
            if (progress.isLevelCompleted(i)) {
                levelButtons[i].setText("✓ Level " + (i+1));
                levelButtons[i].setEnabled(false);
                levelButtons[i].setToolTipText("Level sudah selesai");
            } else if (i > 0 && !progress.isLevelCompleted(i-1)) {
                levelButtons[i].setEnabled(false);
                levelButtons[i].setToolTipText("Selesaikan level " + i + " terlebih dahulu");
            }
        }
        
        if (progress.isLevelCompleted(4)) { 
            SkorBtn.setEnabled(true);
            SkorBtn.setToolTipText("Lihat skor akhir");
        } else {
            SkorBtn.setEnabled(false);
            SkorBtn.setToolTipText("Selesaikan Level 5 terlebih dahulu");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RulesBtn = new javax.swing.JButton();
        L1Btn = new javax.swing.JButton();
        L2Btn = new javax.swing.JButton();
        L5Btn = new javax.swing.JButton();
        L4Btn = new javax.swing.JButton();
        L3Btn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        SkorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RulesBtn.setBackground(new java.awt.Color(126, 163, 86));
        RulesBtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        RulesBtn.setForeground(new java.awt.Color(255, 255, 255));
        RulesBtn.setText("Rules");
        RulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RulesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 60));

        L1Btn.setText("01");
        L1Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        L1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(L1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 50));

        L2Btn.setBackground(new java.awt.Color(229, 131, 81));
        L2Btn.setText("02");
        L2Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        L2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(L2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 50));

        L5Btn.setText("05");
        L5Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        L5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5BtnActionPerformed(evt);
            }
        });
        jPanel1.add(L5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 50, 50));

        L4Btn.setBackground(new java.awt.Color(118, 153, 193));
        L4Btn.setForeground(new java.awt.Color(255, 255, 255));
        L4Btn.setText("04");
        L4Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        L4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4BtnActionPerformed(evt);
            }
        });
        jPanel1.add(L4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, 50));

        L3Btn.setBackground(new java.awt.Color(126, 163, 86));
        L3Btn.setForeground(new java.awt.Color(255, 255, 255));
        L3Btn.setText("03");
        L3Btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        L3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3BtnActionPerformed(evt);
            }
        });
        jPanel1.add(L3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 50, 50));

        CloseBtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(229, 131, 81));
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        resetBtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(229, 131, 81));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        SkorBtn.setBackground(new java.awt.Color(229, 131, 81));
        SkorBtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        SkorBtn.setForeground(new java.awt.Color(255, 255, 255));
        SkorBtn.setText("Final Skor");
        SkorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SkorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgLvl.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1BtnActionPerformed
        if (!progress.isLevelCompleted(0)) {
            new Satu().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_L1BtnActionPerformed

    private void L2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2BtnActionPerformed
        if (progress.isLevelCompleted(0) && !progress.isLevelCompleted(1)) {
            new Dua().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_L2BtnActionPerformed

    private void L3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3BtnActionPerformed
        if (progress.isLevelCompleted(1) && !progress.isLevelCompleted(2)) {
            new Tiga().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_L3BtnActionPerformed

    private void L4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4BtnActionPerformed
        if (progress.isLevelCompleted(2) && !progress.isLevelCompleted(3)) {
            new Empat().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_L4BtnActionPerformed

    private void L5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5BtnActionPerformed
        if (progress.isLevelCompleted(3) && !progress.isLevelCompleted(4)) {
            new Lima().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_L5BtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Reset semua progress? Skor akan kembali ke 0.",
            "Konfirmasi Reset",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            GameProgress.getInstance().resetProgress();
            new Level().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void RulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesBtnActionPerformed
        new Rules().setVisible(true);
        this.dispose();    }//GEN-LAST:event_RulesBtnActionPerformed

    private void SkorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkorBtnActionPerformed
        new Skor(progress.getTotalScore()).setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_SkorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton L1Btn;
    private javax.swing.JButton L2Btn;
    private javax.swing.JButton L3Btn;
    private javax.swing.JButton L4Btn;
    private javax.swing.JButton L5Btn;
    private javax.swing.JButton RulesBtn;
    private javax.swing.JButton SkorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
