package Tampilan;

import Kelas.GameProgress;
import javax.swing.JOptionPane;

public class Lima extends javax.swing.JFrame {
    private final GameProgress progress;
    private int remainingLives = 3;
    private int score;
    private static final String CORRECT_ANSWER = "jagung bakar"; 
    private boolean answeredCorrectly = false;
    private static final String[] HINTS = {
        "Makanan yang terbuat dari biji-bijian yang dipanggang",
        "Sering dijual di pinggir jalan dengan bumbu khusus",
        "Bahan utamanya biasa digunakan untuk membuat popcorn"
    };
    private int currentHintIndex = 0;
    
    Lima() {
        this.progress = GameProgress.getInstance();
        this.score = progress.getTotalScore();
        initComponents();
        NextBtn1.setEnabled(false); 
        ExitBtn.setEnabled(true);
        HintBtn.setEnabled(true);
        
        setLocationRelativeTo(null);
        SkorTxt.setText(String.valueOf(this.score));
        BenarSalahTxt.setEditable(false);
        setTitle("Level 05");
        SkorTxt.setText(String.valueOf(score)); 
        InfoTxt.setEditable(false);
        InfoTxt.setText("Silakan tebak gambar di sebelah kiri!"); 
    }
    
    private void completeLevel() {
        if (answeredCorrectly) {
            progress.completeLevel(4, remainingLives);
            new Level().setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Gambar1 = new javax.swing.JLabel();
        KetikJwbTxt = new javax.swing.JTextField();
        CekBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        heart2 = new javax.swing.JLabel();
        heart1 = new javax.swing.JLabel();
        SkorTxt = new javax.swing.JTextField();
        heart3 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        NextBtn1 = new javax.swing.JButton();
        BenarSalahTxt = new javax.swing.JTextField();
        InfoTxt = new javax.swing.JTextField();
        HintBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gambar1.setBackground(new java.awt.Color(204, 255, 204));
        Gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.png"))); // NOI18N
        jPanel1.add(Gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 250));

        KetikJwbTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        KetikJwbTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KetikJwbTxtActionPerformed(evt);
            }
        });
        jPanel1.add(KetikJwbTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 235, 34));

        CekBtn.setBackground(new java.awt.Color(126, 163, 86));
        CekBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        CekBtn.setForeground(new java.awt.Color(255, 255, 255));
        CekBtn.setText("Cek ");
        CekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CekBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 70, 33));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Skor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        heart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/heartMini.png"))); // NOI18N
        heart2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                heart2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(heart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        heart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/heartMini.png"))); // NOI18N
        heart1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                heart1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(heart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        SkorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkorTxtActionPerformed(evt);
            }
        });
        jPanel1.add(SkorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 30));

        heart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/heartMini.png"))); // NOI18N
        heart3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                heart3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(heart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        ExitBtn.setBackground(new java.awt.Color(126, 163, 86));
        ExitBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ExitBtn.setText("Keluar");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 35));

        NextBtn1.setBackground(new java.awt.Color(126, 163, 86));
        NextBtn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        NextBtn1.setText("Next");
        NextBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(NextBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 35));

        BenarSalahTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenarSalahTxtActionPerformed(evt);
            }
        });
        jPanel1.add(BenarSalahTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 90, 33));

        InfoTxt.setBackground(new java.awt.Color(176, 208, 235));
        InfoTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        InfoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(InfoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 270, 50));

        HintBtn.setBackground(new java.awt.Color(204, 0, 51));
        HintBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        HintBtn.setForeground(new java.awt.Color(255, 255, 255));
        HintBtn.setText("Hint");
        HintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 60, 35));

        jLabel3.setBackground(new java.awt.Color(176, 208, 235));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/BgTebak.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 555, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decreaseLife() {
        if (remainingLives > 0) {
            remainingLives--;
            
            switch (remainingLives) {
                case 2 -> {
                    heart3.setVisible(false);
                    InfoTxt.setText("Salah! Nyawa tersisa: 2");
                }
                case 1 -> {
                    heart2.setVisible(false);
                    InfoTxt.setText("Salah! Nyawa tersisa: 1");
                }
                case 0 -> {
                    heart1.setVisible(false);
                    gameOver();
                }
            }
        }
    }
    
    private void gameOver() {
        JOptionPane.showMessageDialog(this, "Game Over! You've run out of lives.", "Game Over", JOptionPane.INFORMATION_MESSAGE);
        score -= 2; 
        updateScore();
        resetLevel();
    }
    
    private void resetLevel() {
        remainingLives = 3;
        heart1.setVisible(true);
        heart2.setVisible(true);
        heart3.setVisible(true);
        KetikJwbTxt.setText("");
        answeredCorrectly = false;
        currentHintIndex = 0;  
        HintBtn.setEnabled(true);
    }
    
    private void updateScore() {
        SkorTxt.setText(String.valueOf(score));
    }
    
    private void checkAnswer() {
        String userAnswer = KetikJwbTxt.getText().trim().toLowerCase();
        
        if (userAnswer.equals(CORRECT_ANSWER)) {
            ExitBtn.setEnabled(false);
            HintBtn.setEnabled(false);
            answeredCorrectly = true;
            BenarSalahTxt.setText("Benar!");
            
            score += remainingLives;
            updateScore();
            
            InfoTxt.setText("Jawaban benar! Skor +" + remainingLives + ". Klik Next untuk lanjut!");        
            NextBtn1.setEnabled(true);
        } else {
            BenarSalahTxt.setText("Salah!");
            decreaseLife();
        }
    }
    
    private void CekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekBtnActionPerformed
        if (!answeredCorrectly) {
            checkAnswer();
        } else {
            InfoTxt.setText("Anda sudah menjawab dengan benar!");
        }
    }//GEN-LAST:event_CekBtnActionPerformed

    private void KetikJwbTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KetikJwbTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KetikJwbTxtActionPerformed

    private void heart2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_heart2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_heart2AncestorAdded

    private void heart3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_heart3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_heart3AncestorAdded

    private void heart1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_heart1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_heart1AncestorAdded

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        new Level().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void NextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtn1ActionPerformed
        if (answeredCorrectly) {
            completeLevel();
        } else {
            InfoTxt.setText("Anda harus menjawab dengan benar terlebih dahulu!");
        }    }//GEN-LAST:event_NextBtn1ActionPerformed

    private void BenarSalahTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenarSalahTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BenarSalahTxtActionPerformed

    private void SkorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkorTxtActionPerformed

    private void InfoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoTxtActionPerformed

    private void HintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintBtnActionPerformed
        if (currentHintIndex < HINTS.length) {
            JOptionPane.showMessageDialog(this, 
                "Hint " + (currentHintIndex + 1) + ": " + HINTS[currentHintIndex],
                "Petunjuk", 
                JOptionPane.INFORMATION_MESSAGE);
            score -= 1;
            updateScore();
            currentHintIndex++;

            if (currentHintIndex >= HINTS.length) {
                HintBtn.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Tidak ada hint lagi tersedia", 
                "Info", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_HintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BenarSalahTxt;
    private javax.swing.JButton CekBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel Gambar1;
    private javax.swing.JButton HintBtn;
    private javax.swing.JTextField InfoTxt;
    private javax.swing.JTextField KetikJwbTxt;
    private javax.swing.JButton NextBtn1;
    private javax.swing.JTextField SkorTxt;
    private javax.swing.JLabel heart1;
    private javax.swing.JLabel heart2;
    private javax.swing.JLabel heart3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
