package Tampilan;

import Kelas.User;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class LoginFIX extends javax.swing.JFrame {
    public LoginFIX() {
        initComponents();
        setLocationRelativeTo(null); 
        setTitle("Login Game Tebak Gambar");
        infoTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        usernameText = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        infoTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setBackground(new java.awt.Color(204, 255, 204));
        base.setForeground(new java.awt.Color(255, 255, 255));
        base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setText("Tebak Gambar");
        base.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 330, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("   Password ");
        base.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("   Username");
        base.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        passwordText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        base.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, 30));

        usernameText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        usernameText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        base.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 240, 30));

        resetBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(229, 131, 81));
        resetBtn.setText("Reset");
        resetBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        base.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 80, 30));

        loginBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(229, 131, 81));
        loginBtn.setText("Log In");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        base.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, 30));

        infoTxt.setEditable(false);
        infoTxt.setBackground(new java.awt.Color(176, 208, 235));
        infoTxt.setColumns(20);
        infoTxt.setRows(5);
        infoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        infoTxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                infoTxtAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        base.add(infoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 370, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgL.png"))); // NOI18N
        base.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        passwordText.requestFocusInWindow();
    }//GEN-LAST:event_usernameTextActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        usernameText.setText("");
        passwordText.setText("");
        usernameText.requestFocusInWindow();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameText.getText().trim();
        String password = passwordText.getText(); 

        if (username.isEmpty() || password.isEmpty()) {
            infoTxt.setText("Username atau password tidak boleh kosong!");
            infoTxt.setForeground(Color.RED);
            return;
        }

        try {
            User authenticatedUser = User.authenticate(username, password);
            infoTxt.setText("Login berhasil! Selamat datang " + authenticatedUser.getUsername());
            infoTxt.setForeground(new Color(0, 100, 0)); // Warna hijau tua

            Timer timer = new Timer(2000, (e) -> {
                this.dispose();
                Level menuL = new Level();  
                menuL.setVisible(true);
            });
            timer.setRepeats(false);
            timer.start();

        } catch (IllegalArgumentException e) {
            infoTxt.setText(e.getMessage());
            infoTxt.setForeground(Color.RED);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void infoTxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_infoTxtAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_infoTxtAncestorAdded

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, 
            message, 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFIX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JTextArea infoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

    private boolean authenticate(String username, String password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void openMainMenu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}


